"""Extract the complete 4B3960 definition table from the identified research PE."""
import argparse
import hashlib
import struct
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument('binary', type=Path)
p.add_argument('output', type=Path)
a = p.parse_args()
raw = a.binary.read_bytes()
digest = hashlib.sha256(raw).hexdigest()
assert digest == 'bec2375e2c4c1073e3bf7761571470c430de251de74b452dbb86537348ef5290'
pe = struct.unpack_from('<I', raw, 60)[0]
base = struct.unpack_from('<I', raw, pe + 24 + 28)[0]
n = struct.unpack_from('<H', raw, pe + 6)[0]
sections = pe + 24 + struct.unpack_from('<H', raw, pe + 20)[0]
def offset(va):
    for i in range(n):
        _, rva, size, pos = struct.unpack_from('<IIII', raw, sections + 40*i + 8)
        if rva <= va-base < rva+size:
            return pos+va-base-rva
    raise ValueError(hex(va))

va = 0xc64110
rows = []
seen = set()
while True:
    at = offset(va)
    identity = struct.unpack_from('<H', raw, at)[0]
    if identity == 0xffff:
        break
    assert identity < 512 and identity not in seen
    seen.add(identity)
    values = struct.unpack_from('<iiii', raw, at+4)
    rows.append('    {%d, %s}, // %08X' % (identity, ', '.join(map(str, values)), va))
    va += 20
assert va == 0xc64a70
text = '// Generated by tools/extract-parameter-definitions.py; do not hand edit.\n'
text += '// Research SR_GameServer.exe SHA256: ' + digest + '\n'
text += '\n'.join(rows) + '\n'
a.output.write_text(text, encoding='utf-8', newline='\n')
print(len(rows), 'native parameter definitions written')
